### ISSUE TITLE
JsonVariationDetail Crash

### ISSUE THREAD

**Issue by brito-rbi** [launchdarkly/react-native-client-sdk#209]
**Is this a support request?**
No.

**Describe the bug**
There is a crash on iOS related to the `jsonVariationDetail` function. The crash is specifically happening on `LaunchdarklyReactNativeClient.swift - Line 156`

**To reproduce**
We're unable to reproduce, but we see the crash in the wild.

**Expected behavior**
Fetching JSON Variation Detail should not crash the app.

**Logs**
[com.bk.pop-us-mobile_issue_cadb1a4048ee1e1e55286f65c6e71408_crash_session_bba2701389574671b5ba84168ee04364_DNE_0_v2_stacktrace.txt](https://github.com/launchdarkly/react-native-client-sdk/files/10983808/com.bk.pop-us-mobile_issue_cadb1a4048ee1e1e55286f65c6e71408_crash_session_bba2701389574671b5ba84168ee04364_DNE_0_v2_stacktrace.txt)

**SDK version**
Noticed in 6.2.4 upgraded to 7.0.3 which fixed another issue with `jsonVariationDetail`. 

**Language version, developer tools**
`react-native@0.70.5`

**OS/platform**
iOS 16.3.1 iPhone 14

**Additional context**
N/A

**Comment by yusinto** [comment]
This was also fixed in [6.3.2](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.3.2), but please upgrade to the latest 6.x to fix this and another unrelated proguard issue. The latest at this time of writing is [6.3.3](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.3.3).

**Comment by brito-rbi** [comment]
> This was also fixed in [6.3.2](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.3.2), but please upgrade to the latest 6.x to fix this and another unrelated proguard issue. The latest at this time of writing is [6.3.3](https://github.com/launchdarkly/react-native-client-sdk/releases/tag/6.3.3).

Thanks for the quick reply, so is this not fixed in 7.0.3?

**Comment by louis-launchdarkly** [comment]
Hello @brito-rbi, according to the changelog, the issue was also fixed in 7.0.3 (as we merged the contribution from the contributor.) So you should have no issue if you are using the latest RN SDK 6.x or 7.x. LaunchDarkly at this point recommends using the 7.x SDK as that provides the support for Contexts.

Please let us know if you have any other questions or still experience the issue when using the latest 6.x or 7.x

**Comment by brito-rbi** [comment]
> Please let us know if you have any other questions or still experience the issue when using the latest 6.x or 7.x

@louis-launchdarkly apologies that it wasn't clear, but we're still experiencing this issue in the latest 7.x SDK

**Comment by louis-launchdarkly** [comment]
@brito-rbi We will continue this conversation through the support ticket you have open with us, as we will need to ask environment specific information to try reproducing this.

If anyone else encounters a similar issue, please reach out to us via a support ticket by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com

**Comment by louis-launchdarkly** [comment]
This is resolved through the support request. In general, because the Context shape looks a bit different from the previous User shape, we recommend reading https://docs.launchdarkly.com/sdk/client-side/react/react-native-migration-6-to-7#understanding-changes-to-built-in-and-custom-attributes when upgrading the LaunchDarkly SDK from 6.x to 7.x
